<?php

declare(strict_types=1);

/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\MusicRadio\Migration;

use OCA\MusicRadio\AppInfo\Application;
use OCP\Files\AppData\IAppDataFactory;
use OCP\Files\NotFoundException;
use OCP\Files\SimpleFS\ISimpleFolder;
use OCP\IConfig;
use OCP\Migration\IOutput;
use OCP\Migration\IRepairStep;
use Psr\Log\LoggerInterface;

/**
 * Throw away the favicon Nextcloud generated from an older version of this app's icon.
 *
 * The theming app renders each app's favicon and touch icon once and caches the result
 * under a key made of **the app id and the instance's primary colour** — nothing about the
 * icon itself. So shipping a changed `img/app.svg` does not invalidate anything, and every
 * instance that ever rendered the old one keeps serving it indefinitely. The symptom is a
 * browser tab showing the previous icon, typically the wrong colour, while the header (which
 * is served the raw SVG) looks correct.
 *
 * That is why this exists rather than the icon simply being fixed: the icon *was* fixed, and
 * the stale render outlived it. An administrator can clear it with a cachebuster bump, but
 * expecting them to know that after every release is not reasonable.
 *
 * Only this app's own entries are removed, rather than bumping theming's cachebuster, which
 * would discard every app's icons and every generated stylesheet on the instance. Failure is
 * logged and ignored — a stale favicon must never be the reason an upgrade fails.
 */
class ClearThemingIconCache implements IRepairStep {

	/** How many previous cachebuster generations to look through. */
	private const GENERATIONS_TO_SWEEP = 20;

	public function __construct(
		private IAppDataFactory $appDataFactory,
		private IConfig $config,
		private LoggerInterface $logger,
	) {
	}

	public function getName(): string {
		return 'Clear cached Music Radio icons generated by the theming app';
	}

	public function run(IOutput $output): void {
		try {
			$global = $this->appDataFactory->get('theming')->getFolder('global');
		} catch (NotFoundException) {
			// Theming has never generated anything, which is the happy case.
			return;
		} catch (\Throwable $e) {
			$this->logger->debug('Could not reach the theming cache', [
				'app' => Application::APP_ID,
				'exception' => $e,
			]);

			return;
		}

		$removed = $this->purge($global);

		// The icons live one level down, in a folder named after theming's cachebuster
		// value, and old generations are not always tidied up. Those subfolders have to be
		// asked for by name: ISimpleFolder::getDirectoryListing() maps anything that is not
		// a file to null and filters it out, so a folder is simply invisible through it —
		// which is why the first version of this step found nothing and reported success.
		foreach ($this->cacheGenerations() as $name) {
			try {
				$removed += $this->purge($global->getFolder($name));
			} catch (NotFoundException) {
				// That generation was already cleaned up.
			} catch (\Throwable $e) {
				$this->logger->debug('Could not read a theming cache generation', [
					'app' => Application::APP_ID,
					'generation' => $name,
					'exception' => $e,
				]);
			}
		}

		if ($removed > 0) {
			$output->info(sprintf('Removed %d cached icon(s); theming will render them again.', $removed));
		}
	}

	/**
	 * Every cachebuster value that could still have a folder, newest first.
	 *
	 * Counted down from the current one rather than discovered, for the reason above. The
	 * bound keeps a long-lived instance with a high cachebuster from walking thousands of
	 * folders that have not existed for years.
	 *
	 * @return list<string>
	 */
	private function cacheGenerations(): array {
		$current = (int)$this->config->getAppValue('theming', 'cachebuster', '0');
		$oldest = max(0, $current - self::GENERATIONS_TO_SWEEP);

		$names = [];
		for ($value = $current; $value >= $oldest; $value--) {
			$names[] = (string)$value;
		}

		return $names;
	}

	private function purge(ISimpleFolder $folder): int {
		$removed = 0;

		try {
			$entries = $folder->getDirectoryListing();
		} catch (\Throwable) {
			return 0;
		}

		foreach ($entries as $entry) {
			// Named "favIcon-<app>#<colour>" and "touchIcon-<app>#<colour>". Matching on the
			// app id alone would also catch another app whose id contained this one's, which
			// is why the separator is part of the test.
			if (!str_contains($entry->getName(), '-' . Application::APP_ID . '#')) {
				continue;
			}

			try {
				$entry->delete();
				$removed++;
			} catch (\Throwable $e) {
				$this->logger->debug('Could not remove a cached icon', [
					'app' => Application::APP_ID,
					'name' => $entry->getName(),
					'exception' => $e,
				]);
			}
		}

		return $removed;
	}
}
